"""Paired H1 collection for fixed and adaptive frequency controls.

This module is deliberately separate from :mod:`collect`: it supports the H1-only
offset sensitivity notebook without changing the data or checkpoints used by the
full Bayesian workflow.  Every observation contains both contrasts on the same
model, lock, background and phase.  The lock recovery is therefore evaluated once
and shared by the fixed- and adaptive-offset estimands.

Real collection writes one shard per geometry plus a JSON design manifest.  Smoke
data generated by :func:`synthetic_paired_data` never load Chronos and are marked
``reportable=False`` so they cannot be confused with empirical results.
"""

from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import asdict, dataclass, replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Sequence

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import probe_lib as pl

# Frozen for the H1 sensitivity analysis.  This is intentionally not an alias of
# pl.BAYES_MODELS: a later registry change must not silently alter the population.
FROZEN_BAYES_MODELS: tuple[tuple[int, int], ...] = (
    (8, 4),
    (8, 5),
    (8, 8),
    (16, 4),
    (16, 8),
    (16, 12),
    (16, 15),
    (16, 16),
    (24, 8),
    (24, 12),
    (24, 15),
    (24, 16),
    (24, 20),
    (24, 24),
    (32, 8),
    (32, 12),
    (32, 15),
    (32, 16),
    (32, 20),
    (32, 24),
    (32, 32),
)

MODULE_VERSION = 3
SHARD_PREFIX = "h1_paired_offsets"
MERGED_NAME = f"{SHARD_PREFIX}.parquet"
MANIFEST_NAME = "h1_offset_manifest.json"


@dataclass(frozen=True)
class H1OffsetConfig:
    """Complete design configuration for the paired H1 offset experiment."""

    fixed_offset_hz: float = 1.0
    guard_hz: float = 1.0
    adaptive_step_hz: float = 0.05
    n_phase: int = 10
    n_bg: int = 100
    generators: tuple[str, ...] = pl.GENERATORS
    batch_size: int = 64
    device: str | None = None
    seed: int = 42
    background_seed0: int = 10_000
    epsilon: float = 0.01
    live_threshold: float = 0.05
    smoke: bool = False

    def __post_init__(self) -> None:
        if self.fixed_offset_hz <= 0:
            raise ValueError("fixed_offset_hz must be positive")
        if self.guard_hz < 0:
            raise ValueError("guard_hz cannot be negative")
        if self.adaptive_step_hz <= 0:
            raise ValueError("adaptive_step_hz must be positive")
        if self.n_phase < 1 or self.n_bg < 1 or self.batch_size < 1:
            raise ValueError("n_phase, n_bg and batch_size must be positive integers")
        if not self.generators:
            raise ValueError("at least one background generator is required")
        if len(set(self.generators)) != len(self.generators):
            raise ValueError("generators must be unique")
        if self.epsilon <= 0:
            raise ValueError("epsilon must be positive")
        if self.live_threshold < 0:
            raise ValueError("live_threshold cannot be negative")

    @classmethod
    def smoke_config(cls, **overrides: object) -> "H1OffsetConfig":
        """Return a tiny real-pipeline configuration whose outputs are non-reportable."""

        cfg = cls(
            n_phase=2,
            n_bg=1,
            generators=("tsmixup",),
            batch_size=32,
            smoke=True,
        )
        return replace(cfg, **overrides)


WIDE_COLUMNS: tuple[str, ...] = (
    "pair_key",
    "data_origin",
    "reportable",
    "model",
    "P",
    "S",
    "overlap",
    "generator",
    "bg_id",
    "f_lock",
    "family",
    "cpp",
    "phase_idx",
    "phase",
    "delta_fixed_hz",
    "delta_adaptive_hz",
    "f_fixed_lo",
    "f_fixed_hi",
    "f_adaptive_lo",
    "f_adaptive_hi",
    "R_lock",
    "R_fixed_lo",
    "R_fixed_hi",
    "R_adaptive_lo",
    "R_adaptive_hi",
    "R_ctrl_fixed",
    "R_ctrl_adaptive",
    "dphase_lock",
    "d_fixed",
    "d_adaptive",
    "live_fixed",
    "live_adaptive",
)

LONG_COLUMNS: tuple[str, ...] = (
    "pair_key",
    "data_origin",
    "reportable",
    "model",
    "P",
    "S",
    "overlap",
    "generator",
    "bg_id",
    "f_lock",
    "family",
    "cpp",
    "phase_idx",
    "phase",
    "offset_kind",
    "delta_hz",
    "f_lo",
    "f_hi",
    "R_lock",
    "R_lo",
    "R_hi",
    "R_ctrl",
    "dphase_lock",
    "d",
    "live",
)


def _cfg(config: H1OffsetConfig | None) -> H1OffsetConfig:
    return config if config is not None else H1OffsetConfig()


def _model_tag(model: tuple[int, int]) -> str:
    return pl.model_tag(int(model[0]), int(model[1]))


def _normalise_models(models: Sequence[tuple[int, int]]) -> tuple[tuple[int, int], ...]:
    out = tuple((int(P), int(S)) for P, S in models)
    if not out:
        raise ValueError("models cannot be empty")
    if len(set(out)) != len(out):
        raise ValueError("models contains duplicates")
    unknown = [m for m in out if m not in FROZEN_BAYES_MODELS]
    if unknown:
        raise ValueError(f"models outside FROZEN_BAYES_MODELS: {unknown}")
    return out


def _config_payload(config: H1OffsetConfig) -> dict[str, object]:
    payload = asdict(config)
    payload["generators"] = list(config.generators)
    return payload


def _config_fingerprint(config: H1OffsetConfig) -> str:
    raw = json.dumps(_config_payload(config), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _file_sha256(path: Path) -> str:
    """Return a streaming content digest for provenance-sensitive source files."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _directory_sha256(root: Path) -> str:
    """Hash names and contents of a resolved local checkpoint directory."""

    digest = hashlib.sha256()
    files = sorted(path for path in root.rglob("*") if path.is_file())
    if not files:
        raise ValueError(f"local checkpoint directory is empty: {root}")
    for path in files:
        relative = path.relative_to(root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(8, "big"))
        digest.update(relative)
        digest.update(path.stat().st_size.to_bytes(8, "big"))
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    return digest.hexdigest()


def _source_provenance() -> dict[str, dict[str, str]]:
    """Source identities that must match before an old collection can resume."""

    paths = {
        "h1_offset_lib": Path(__file__).resolve(),
        "probe_lib": Path(pl.__file__).resolve(),
    }
    return {
        name: {"file": path.name, "sha256": _file_sha256(path)}
        for name, path in paths.items()
    }


def _experimental_constants() -> dict[str, object]:
    return {
        "fs_hz": int(pl.FS),
        "context_samples": int(pl.CTX),
        "prediction_samples": int(pl.PRED),
        "analysis_band_hz": [float(pl.BAND[0]), float(pl.BAND[1])],
        "tone_snr": float(pl.TONE_SNR),
        "checkpoint_contract": "p{P}-s{S}-seed42 retrained geometry",
    }


def _excluded_site_records(
    config: H1OffsetConfig,
    models: Sequence[tuple[int, int]],
) -> list[dict[str, object]]:
    """Describe every lock removed from the common fixed/adaptive support."""

    records: list[dict[str, object]] = []
    for P, S in models:
        retained = {
            round(float(value), 6)
            for value in select_common_sites(P, S, config)["f_lock"]
        }
        for f_lock in pl.f_lock(P, S):
            if round(float(f_lock), 6) in retained:
                continue
            adaptive = pl.control_offset(
                P,
                S,
                f_lock,
                guard=config.guard_hz,
                step=config.adaptive_step_hz,
            )
            fixed_clean = _controls_are_clean(
                f_lock, config.fixed_offset_hz, P, S, config.guard_hz
            )
            adaptive_clean = bool(
                np.isfinite(adaptive)
                and _controls_are_clean(f_lock, adaptive, P, S, config.guard_hz)
            )
            reasons = []
            if not fixed_clean:
                reasons.append("fixed_control_out_of_band_or_lock_collision")
            if not adaptive_clean:
                reasons.append("adaptive_control_out_of_band_or_lock_collision")
            records.append(
                {
                    "model": _model_tag((P, S)),
                    "P": int(P),
                    "S": int(S),
                    "f_lock_hz": float(f_lock),
                    "fixed_offset_hz": float(config.fixed_offset_hz),
                    "adaptive_offset_hz": (
                        float(adaptive) if np.isfinite(adaptive) else None
                    ),
                    "reasons": reasons,
                }
            )
    return records


def _design_fingerprint(
    config: H1OffsetConfig,
    models: Sequence[tuple[int, int]],
) -> str:
    """Hash every choice that makes an existing shard safe or unsafe to resume."""

    payload = {
        "schema": "patchaliasing.h1-paired-offsets",
        "module_version": MODULE_VERSION,
        "wide_columns": list(WIDE_COLUMNS),
        "config": _config_payload(config),
        "frozen_bayes_models": [list(model) for model in FROZEN_BAYES_MODELS],
        "models_requested": [list(model) for model in models],
        "experimental_constants": _experimental_constants(),
        "source_provenance": _source_provenance(),
    }
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def design_fingerprint(
    config: H1OffsetConfig,
    models: Sequence[tuple[int, int]] = FROZEN_BAYES_MODELS,
) -> str:
    """Public collection-design identity used to isolate expensive data shards."""

    return _design_fingerprint(config, _normalise_models(models))


def _pair_key(
    model: str, generator: str, bg_id: int, f_lock: float, phase_idx: int
) -> str:
    return (
        f"{model}|{generator}|bg{int(bg_id):03d}|"
        f"f{float(f_lock):.6f}|phase{int(phase_idx):02d}"
    )


def _controls_are_clean(
    f_lock: float,
    delta: float,
    P: int,
    S: int,
    guard: float,
    *,
    atol: float = 1e-6,
) -> bool:
    """Numerically stable form of ``pl.controls_are_clean``.

    ``control_offset`` rounds its accepted result to six decimals.  For offsets
    such as 9.666667 Hz that can turn an exact 1 Hz separation into
    0.99999999999999 in binary floating point.  The registered rule is "at least
    the guard", so only sub-microhertz arithmetic noise is tolerated here.
    """

    others = [x for x in pl.f_lock(P, S) if abs(x - f_lock) > atol]
    for control in (f_lock - delta, f_lock + delta):
        if control < pl.BAND[0] - atol or control > pl.BAND[1] + atol:
            return False
        if any(abs(control - other) < guard - atol for other in others):
            return False
    return True


def select_common_sites(
    P: int,
    S: int,
    config: H1OffsetConfig | None = None,
) -> pd.DataFrame:
    """Return lock sites valid for both fixed and adaptive controls.

    A site is retained only when both symmetric fixed controls and both adaptive
    controls are inside the analysis band and at least ``guard_hz`` from every
    *other* member of the geometry's lock union.
    """

    cfg = _cfg(config)
    geometry = (int(P), int(S))
    if geometry not in FROZEN_BAYES_MODELS:
        raise ValueError(f"geometry {geometry} is not in FROZEN_BAYES_MODELS")

    rows: list[dict[str, object]] = []
    for f_lock in pl.f_lock(P, S):
        adaptive = pl.control_offset(
            P,
            S,
            f_lock,
            guard=cfg.guard_hz,
            step=cfg.adaptive_step_hz,
        )
        fixed_clean = _controls_are_clean(
            f_lock,
            cfg.fixed_offset_hz,
            P,
            S,
            cfg.guard_hz,
        )
        adaptive_clean = bool(
            np.isfinite(adaptive)
            and _controls_are_clean(f_lock, adaptive, P, S, cfg.guard_hz)
        )
        if not (fixed_clean and adaptive_clean):
            continue

        rows.append(
            {
                "model": pl.model_tag(P, S),
                "P": int(P),
                "S": int(S),
                "f_lock": float(f_lock),
                "family": pl.lock_family(f_lock, P, S),
                "delta_fixed_hz": float(cfg.fixed_offset_hz),
                "delta_adaptive_hz": float(adaptive),
                "f_fixed_lo": float(f_lock - cfg.fixed_offset_hz),
                "f_fixed_hi": float(f_lock + cfg.fixed_offset_hz),
                "f_adaptive_lo": float(f_lock - adaptive),
                "f_adaptive_hi": float(f_lock + adaptive),
            }
        )

    columns = (
        "model",
        "P",
        "S",
        "f_lock",
        "family",
        "delta_fixed_hz",
        "delta_adaptive_hz",
        "f_fixed_lo",
        "f_fixed_hi",
        "f_adaptive_lo",
        "f_adaptive_hi",
    )
    return (
        pd.DataFrame(rows, columns=columns).sort_values("f_lock").reset_index(drop=True)
    )


def _derive_contrasts(frame: pd.DataFrame, config: H1OffsetConfig) -> pd.DataFrame:
    out = frame.copy()
    eps = config.epsilon

    out["R_ctrl_fixed"] = 0.5 * (out["R_fixed_lo"] + out["R_fixed_hi"])
    out["R_ctrl_adaptive"] = 0.5 * (out["R_adaptive_lo"] + out["R_adaptive_hi"])
    out["d_fixed"] = np.log(out["R_lock"] + eps) - 0.5 * (
        np.log(out["R_fixed_lo"] + eps) + np.log(out["R_fixed_hi"] + eps)
    )
    out["d_adaptive"] = np.log(out["R_lock"] + eps) - 0.5 * (
        np.log(out["R_adaptive_lo"] + eps) + np.log(out["R_adaptive_hi"] + eps)
    )
    out["live_fixed"] = (
        out[["R_lock", "R_fixed_lo", "R_fixed_hi"]].max(axis=1) > config.live_threshold
    )
    out["live_adaptive"] = (
        out[["R_lock", "R_adaptive_lo", "R_adaptive_hi"]].max(axis=1)
        > config.live_threshold
    )
    return out


def _validate_design_completeness(
    frame: pd.DataFrame,
    config: H1OffsetConfig,
) -> None:
    """Check the site -> generator -> background -> phase nesting."""

    origins = set(frame["data_origin"].astype(str))
    if len(origins) != 1:
        raise ValueError(f"one paired table cannot mix data origins: {sorted(origins)}")
    synthetic = next(iter(origins)) == "synthetic_smoke"

    for (P, S), geometry_rows in frame.groupby(["P", "S"], sort=False):
        P, S = int(P), int(S)
        tag = pl.model_tag(P, S)
        expected_sites = select_common_sites(P, S, config)
        expected_frequencies = set(np.round(expected_sites["f_lock"], 6))
        actual_frequencies = set(np.round(geometry_rows["f_lock"], 6))
        if actual_frequencies != expected_frequencies:
            missing = sorted(expected_frequencies - actual_frequencies)
            extra = sorted(actual_frequencies - expected_frequencies)
            raise ValueError(
                f"{tag}: incomplete common-site coverage; missing={missing}, extra={extra}"
            )

        actual_generators = tuple(
            sorted(geometry_rows["generator"].astype(str).unique())
        )
        expected_generators = tuple(sorted(config.generators))
        if actual_generators != expected_generators:
            raise ValueError(
                f"{tag}: incomplete generator coverage; "
                f"expected={expected_generators}, actual={actual_generators}"
            )

        background_sets: dict[str, tuple[int, ...]] = {}
        for generator, generator_rows in geometry_rows.groupby("generator", sort=False):
            ids = tuple(sorted(generator_rows["bg_id"].astype(int).unique()))
            background_sets[str(generator)] = ids
        if len(set(background_sets.values())) != 1:
            raise ValueError(
                f"{tag}: generators do not share the same background-id coverage"
            )
        actual_backgrounds = next(iter(background_sets.values()))
        expected_backgrounds = (
            tuple(range(len(actual_backgrounds)))
            if synthetic
            else tuple(range(config.n_bg))
        )
        if actual_backgrounds != expected_backgrounds:
            raise ValueError(
                f"{tag}: incomplete background coverage; "
                f"expected={expected_backgrounds}, actual={actual_backgrounds}"
            )

        n_generator_backgrounds = len(actual_generators) * len(actual_backgrounds)
        for f_lock in sorted(expected_frequencies):
            site_rows = geometry_rows[
                np.isclose(geometry_rows["f_lock"], f_lock, atol=1e-6)
            ]
            counts = site_rows.groupby(["generator", "bg_id"], sort=False).size()
            if len(counts) != n_generator_backgrounds or counts.nunique() != 1:
                raise ValueError(
                    f"{tag} at {f_lock:g} Hz: incomplete paired phase nesting"
                )

            if synthetic:
                observed_phase_count = int(counts.iloc[0])
                phases = pl.phases_Sf(float(f_lock), observed_phase_count)
            else:
                phases = pl.phases_Sf(float(f_lock), config.n_phase)
            if int(counts.iloc[0]) != len(phases):
                raise ValueError(f"{tag} at {f_lock:g} Hz: incomplete phase coverage")

            expected_phase_ids = tuple(range(len(phases)))
            for (_generator, _bg_id), pair_rows in site_rows.groupby(
                ["generator", "bg_id"], sort=False
            ):
                actual_phase_ids = tuple(sorted(pair_rows["phase_idx"].astype(int)))
                if actual_phase_ids != expected_phase_ids:
                    raise ValueError(
                        f"{tag} at {f_lock:g} Hz: incomplete phase indices"
                    )
                ordered = pair_rows.sort_values("phase_idx")
                if not np.allclose(ordered["phase"], phases, atol=1e-10):
                    raise ValueError(
                        f"{tag} at {f_lock:g} Hz: phase values do not match phases_Sf"
                    )


def _collect_geometry(probe: object, config: H1OffsetConfig) -> pd.DataFrame:
    P, S = int(getattr(probe, "P")), int(getattr(probe, "S"))
    tag = pl.model_tag(P, S)
    sites = select_common_sites(P, S, config)
    if sites.empty:
        raise ValueError(f"{tag}: no site is valid under both offset rules")

    blocks: list[pd.DataFrame] = []
    for generator in config.generators:
        backgrounds = pl.background_pool(
            generator,
            config.n_bg,
            pl.CTX + pl.PRED,
            config.background_seed0,
        )
        for bg_id, background in enumerate(backgrounds):
            contexts: list[np.ndarray] = []
            futures: list[np.ndarray] = []
            frequencies: list[float] = []
            metadata: list[dict[str, object]] = []

            for site in sites.itertuples(index=False):
                phases = pl.phases_Sf(site.f_lock, config.n_phase)
                for phase_idx, phase in enumerate(phases):
                    key = _pair_key(tag, generator, bg_id, site.f_lock, phase_idx)
                    base = {
                        "pair_key": key,
                        "data_origin": "chronos_smoke" if config.smoke else "chronos",
                        "reportable": not config.smoke,
                        "model": tag,
                        "P": P,
                        "S": S,
                        "overlap": (P - S) / P,
                        "generator": generator,
                        "bg_id": int(bg_id),
                        "f_lock": float(site.f_lock),
                        "family": site.family,
                        "cpp": float(site.f_lock * P / pl.FS),
                        "phase_idx": int(phase_idx),
                        "phase": float(phase),
                        "delta_fixed_hz": float(site.delta_fixed_hz),
                        "delta_adaptive_hz": float(site.delta_adaptive_hz),
                        "f_fixed_lo": float(site.f_fixed_lo),
                        "f_fixed_hi": float(site.f_fixed_hi),
                        "f_adaptive_lo": float(site.f_adaptive_lo),
                        "f_adaptive_hi": float(site.f_adaptive_hi),
                    }
                    roles = (
                        ("lock", site.f_lock),
                        ("fixed_lo", site.f_fixed_lo),
                        ("fixed_hi", site.f_fixed_hi),
                        ("adaptive_lo", site.f_adaptive_lo),
                        ("adaptive_hi", site.f_adaptive_hi),
                    )
                    for role, frequency in roles:
                        full = pl.build_context(
                            background,
                            float(frequency),
                            float(phase),
                            pl.CTX + pl.PRED,
                        )
                        contexts.append(np.asarray(full[: pl.CTX], dtype=np.float32))
                        futures.append(np.asarray(full[pl.CTX :], dtype=np.float32))
                        frequencies.append(float(frequency))
                        metadata.append({**base, "role": role})

            recovery, phase_error = probe.recovery(
                np.stack(contexts),
                np.stack(futures),
                np.asarray(frequencies, dtype=float),
            )
            measured = pd.DataFrame(metadata)
            measured["R"] = np.asarray(recovery, dtype=float)
            measured["dphase"] = np.asarray(phase_error, dtype=float)

            index_columns = [c for c in WIDE_COLUMNS[:20] if c not in {"R_lock"}]
            response = measured.pivot(
                index=index_columns,
                columns="role",
                values="R",
            ).reset_index()
            response.columns.name = None
            response = response.rename(
                columns={
                    "lock": "R_lock",
                    "fixed_lo": "R_fixed_lo",
                    "fixed_hi": "R_fixed_hi",
                    "adaptive_lo": "R_adaptive_lo",
                    "adaptive_hi": "R_adaptive_hi",
                }
            )
            phase_at_lock = (
                measured.loc[measured["role"] == "lock", ["pair_key", "dphase"]]
                .rename(columns={"dphase": "dphase_lock"})
                .drop_duplicates("pair_key")
            )
            response = response.merge(
                phase_at_lock, on="pair_key", validate="one_to_one"
            )
            blocks.append(_derive_contrasts(response, config))

    out = pd.concat(blocks, ignore_index=True)
    out = out.loc[:, WIDE_COLUMNS]
    out = out.sort_values(
        ["model", "generator", "bg_id", "f_lock", "phase_idx"]
    ).reset_index(drop=True)
    validate_paired_data(out, config)
    return out


def validate_paired_data(
    frame: pd.DataFrame,
    config: H1OffsetConfig | None = None,
    *,
    require_all_models: bool = False,
) -> dict[str, object]:
    """Validate paired completeness, geometry, collision guards and derived values.

    The function raises :class:`ValueError` on the first invalid invariant and
    otherwise returns a compact, JSON-serialisable summary.
    """

    cfg = _cfg(config)
    missing = [column for column in WIDE_COLUMNS if column not in frame.columns]
    if missing:
        raise ValueError(f"paired data missing columns: {missing}")
    if frame.empty:
        raise ValueError("paired data is empty")

    if frame["pair_key"].isna().any() or frame["pair_key"].duplicated().any():
        raise ValueError("pair_key must be present and unique in wide data")
    logical_key = ["model", "generator", "bg_id", "f_lock", "phase_idx"]
    if frame.duplicated(logical_key).any():
        raise ValueError(f"duplicate logical pairs on {logical_key}")

    numeric = [
        "P",
        "S",
        "overlap",
        "bg_id",
        "f_lock",
        "cpp",
        "phase_idx",
        "phase",
        "delta_fixed_hz",
        "delta_adaptive_hz",
        "f_fixed_lo",
        "f_fixed_hi",
        "f_adaptive_lo",
        "f_adaptive_hi",
        "R_lock",
        "R_fixed_lo",
        "R_fixed_hi",
        "R_adaptive_lo",
        "R_adaptive_hi",
        "R_ctrl_fixed",
        "R_ctrl_adaptive",
        "dphase_lock",
        "d_fixed",
        "d_adaptive",
    ]
    values = frame[numeric].to_numpy(dtype=float)
    if not np.isfinite(values).all():
        raise ValueError("paired data contains NaN or infinite numeric values")
    recoveries = frame[
        ["R_lock", "R_fixed_lo", "R_fixed_hi", "R_adaptive_lo", "R_adaptive_hi"]
    ].to_numpy(dtype=float)
    if (recoveries < 0).any():
        raise ValueError("recovery ratios must be non-negative")

    models = set(zip(frame["P"].astype(int), frame["S"].astype(int)))
    unknown = models.difference(FROZEN_BAYES_MODELS)
    if unknown:
        raise ValueError(
            f"data contains geometry outside frozen manifest: {sorted(unknown)}"
        )
    if require_all_models and models != set(FROZEN_BAYES_MODELS):
        absent = set(FROZEN_BAYES_MODELS).difference(models)
        extra = models.difference(FROZEN_BAYES_MODELS)
        raise ValueError(
            f"model coverage mismatch; missing={sorted(absent)}, extra={sorted(extra)}"
        )

    expected_tags = [
        pl.model_tag(int(P), int(S)) for P, S in zip(frame["P"], frame["S"])
    ]
    if not np.array_equal(
        frame["model"].astype(str).to_numpy(), np.asarray(expected_tags)
    ):
        raise ValueError("model tag does not match P/S")
    expected_keys = [
        _pair_key(str(m), str(g), int(b), float(f), int(p))
        for m, g, b, f, p in zip(
            frame["model"],
            frame["generator"],
            frame["bg_id"],
            frame["f_lock"],
            frame["phase_idx"],
        )
    ]
    if not np.array_equal(
        frame["pair_key"].astype(str).to_numpy(), np.asarray(expected_keys)
    ):
        raise ValueError("pair_key is inconsistent with its pairing columns")

    if not np.allclose(frame["delta_fixed_hz"], cfg.fixed_offset_hz, atol=1e-9):
        raise ValueError("fixed offsets do not match H1OffsetConfig.fixed_offset_hz")
    frequency_checks = (
        ("f_fixed_lo", frame["f_lock"] - frame["delta_fixed_hz"]),
        ("f_fixed_hi", frame["f_lock"] + frame["delta_fixed_hz"]),
        ("f_adaptive_lo", frame["f_lock"] - frame["delta_adaptive_hz"]),
        ("f_adaptive_hi", frame["f_lock"] + frame["delta_adaptive_hz"]),
    )
    for column, expected in frequency_checks:
        if not np.allclose(frame[column], expected, atol=1e-6):
            raise ValueError(f"{column} is not symmetric around f_lock")
        if ((frame[column] < pl.BAND[0]) | (frame[column] > pl.BAND[1])).any():
            raise ValueError(f"{column} leaves the analysis band {pl.BAND}")

    sites = frame[
        ["P", "S", "f_lock", "delta_fixed_hz", "delta_adaptive_hz"]
    ].drop_duplicates()
    for row in sites.itertuples(index=False):
        expected_adaptive = pl.control_offset(
            int(row.P),
            int(row.S),
            float(row.f_lock),
            guard=cfg.guard_hz,
            step=cfg.adaptive_step_hz,
        )
        if not np.isfinite(expected_adaptive) or not np.isclose(
            float(row.delta_adaptive_hz), expected_adaptive, atol=1e-6
        ):
            raise ValueError(
                "adaptive offset is not the registered control_offset for its site"
            )
        if not _controls_are_clean(
            float(row.f_lock),
            float(row.delta_fixed_hz),
            int(row.P),
            int(row.S),
            cfg.guard_hz,
        ):
            raise ValueError("fixed controls collide with another lock")
        if not _controls_are_clean(
            float(row.f_lock),
            float(row.delta_adaptive_hz),
            int(row.P),
            int(row.S),
            cfg.guard_hz,
        ):
            raise ValueError("adaptive controls collide with another lock")

    derived = _derive_contrasts(frame, cfg)
    for column in ("R_ctrl_fixed", "R_ctrl_adaptive", "d_fixed", "d_adaptive"):
        if not np.allclose(frame[column], derived[column], atol=1e-10, rtol=1e-9):
            raise ValueError(f"derived column {column} is inconsistent")
    for column in ("live_fixed", "live_adaptive"):
        if not np.array_equal(frame[column].astype(bool), derived[column].astype(bool)):
            raise ValueError(f"derived column {column} is inconsistent")

    origin = frame["data_origin"].astype(str)
    reportable = frame["reportable"].astype(bool)
    forbidden = (
        origin.str.contains("smoke|synthetic", case=False, regex=True) & reportable
    )
    if forbidden.any():
        raise ValueError("smoke or synthetic data must have reportable=False")

    _validate_design_completeness(frame, cfg)

    return {
        "rows": int(len(frame)),
        "pairs": int(frame["pair_key"].nunique()),
        "models": sorted(frame["model"].astype(str).unique().tolist()),
        "lock_sites": int(frame[["model", "f_lock"]].drop_duplicates().shape[0]),
        "data_origins": sorted(origin.unique().tolist()),
        "reportable": bool(reportable.all()),
    }


def to_long_contrasts(frame: pd.DataFrame) -> pd.DataFrame:
    """Convert paired wide data to one fixed and one adaptive row per pair."""

    missing = [column for column in WIDE_COLUMNS if column not in frame.columns]
    if missing:
        raise ValueError(f"paired data missing columns: {missing}")

    base = [
        "pair_key",
        "data_origin",
        "reportable",
        "model",
        "P",
        "S",
        "overlap",
        "generator",
        "bg_id",
        "f_lock",
        "family",
        "cpp",
        "phase_idx",
        "phase",
    ]
    parts: list[pd.DataFrame] = []
    for kind in ("fixed", "adaptive"):
        sources = [
            f"delta_{kind}_hz",
            f"f_{kind}_lo",
            f"f_{kind}_hi",
            "R_lock",
            f"R_{kind}_lo",
            f"R_{kind}_hi",
            f"R_ctrl_{kind}",
            "dphase_lock",
            f"d_{kind}",
            f"live_{kind}",
        ]
        part = frame[base + sources].copy()
        part.insert(len(base), "offset_kind", kind)
        part = part.rename(
            columns={
                f"delta_{kind}_hz": "delta_hz",
                f"f_{kind}_lo": "f_lo",
                f"f_{kind}_hi": "f_hi",
                f"R_{kind}_lo": "R_lo",
                f"R_{kind}_hi": "R_hi",
                f"R_ctrl_{kind}": "R_ctrl",
                f"d_{kind}": "d",
                f"live_{kind}": "live",
            }
        )
        parts.append(part.loc[:, LONG_COLUMNS])

    out = pd.concat(parts, ignore_index=True)
    if out.duplicated(["pair_key", "offset_kind"]).any():
        raise ValueError(
            "long conversion did not preserve one row per pair and offset kind"
        )
    return out.sort_values(
        ["model", "generator", "bg_id", "f_lock", "phase_idx", "offset_kind"]
    ).reset_index(drop=True)


def synthetic_paired_data(
    config: H1OffsetConfig | None = None,
    models: Sequence[tuple[int, int]] = FROZEN_BAYES_MODELS[:2],
    *,
    n_bg: int = 2,
    n_phase: int = 2,
) -> pd.DataFrame:
    """Return deterministic, structurally valid and explicitly non-reportable smoke data."""

    cfg = _cfg(config)
    selected = _normalise_models(models)
    if n_bg < 1 or n_phase < 1:
        raise ValueError("n_bg and n_phase must be positive")
    rng = np.random.default_rng(cfg.seed)
    rows: list[dict[str, object]] = []

    for P, S in selected:
        tag = pl.model_tag(P, S)
        for site in select_common_sites(P, S, cfg).itertuples(index=False):
            phases = pl.phases_Sf(site.f_lock, n_phase)
            for generator in cfg.generators:
                for bg_id in range(n_bg):
                    for phase_idx, phase in enumerate(phases):
                        # Keep a deterministic minority below the live threshold so the
                        # smoke run exercises both the complete and response-conditioned
                        # views instead of making them accidentally identical.
                        dead = (
                            P
                            + S
                            + int(round(site.f_lock))
                            + bg_id
                            + phase_idx
                            + sum(map(ord, generator))
                        ) % 7 == 0
                        baseline_location = -4.4 if dead else -0.05
                        baseline = float(np.exp(rng.normal(baseline_location, 0.08)))
                        R_lock = float(baseline * np.exp(rng.normal(-0.22, 0.04)))
                        R_fixed_lo = float(baseline * np.exp(rng.normal(-0.02, 0.03)))
                        R_fixed_hi = float(baseline * np.exp(rng.normal(0.02, 0.03)))
                        R_adaptive_lo = float(
                            baseline * np.exp(rng.normal(-0.01, 0.04))
                        )
                        R_adaptive_hi = float(baseline * np.exp(rng.normal(0.01, 0.04)))
                        rows.append(
                            {
                                "pair_key": _pair_key(
                                    tag, generator, bg_id, site.f_lock, phase_idx
                                ),
                                "data_origin": "synthetic_smoke",
                                "reportable": False,
                                "model": tag,
                                "P": P,
                                "S": S,
                                "overlap": (P - S) / P,
                                "generator": generator,
                                "bg_id": bg_id,
                                "f_lock": float(site.f_lock),
                                "family": site.family,
                                "cpp": float(site.f_lock * P / pl.FS),
                                "phase_idx": phase_idx,
                                "phase": float(phase),
                                "delta_fixed_hz": float(site.delta_fixed_hz),
                                "delta_adaptive_hz": float(site.delta_adaptive_hz),
                                "f_fixed_lo": float(site.f_fixed_lo),
                                "f_fixed_hi": float(site.f_fixed_hi),
                                "f_adaptive_lo": float(site.f_adaptive_lo),
                                "f_adaptive_hi": float(site.f_adaptive_hi),
                                "R_lock": R_lock,
                                "R_fixed_lo": R_fixed_lo,
                                "R_fixed_hi": R_fixed_hi,
                                "R_adaptive_lo": R_adaptive_lo,
                                "R_adaptive_hi": R_adaptive_hi,
                                "dphase_lock": float(abs(rng.normal(3.0, 1.0))),
                            }
                        )

    frame = _derive_contrasts(pd.DataFrame(rows), cfg).loc[:, WIDE_COLUMNS]
    frame = frame.sort_values(
        ["model", "generator", "bg_id", "f_lock", "phase_idx"]
    ).reset_index(drop=True)
    validate_paired_data(frame, cfg)
    return frame


def _shard_path(out_dir: Path, P: int, S: int) -> Path:
    return out_dir / "raw" / f"{SHARD_PREFIX}__{pl.model_tag(P, S)}.parquet"


def _atomic_parquet(frame: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.stem}.tmp{path.suffix}")
    try:
        frame.to_parquet(temporary, index=False)
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _atomic_json(payload: dict[str, object], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    try:
        temporary.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_manifest(
    config: H1OffsetConfig,
    models: Sequence[tuple[int, int]],
) -> dict[str, object]:
    return {
        "schema": "patchaliasing.h1-paired-offsets",
        "module_version": MODULE_VERSION,
        "status": "running",
        "created_at": _timestamp(),
        "updated_at": _timestamp(),
        "config": _config_payload(config),
        "config_fingerprint": _config_fingerprint(config),
        "design_fingerprint": _design_fingerprint(config, models),
        "seed": config.seed,
        "experimental_constants": _experimental_constants(),
        "source_provenance": _source_provenance(),
        "excluded_sites": _excluded_site_records(config, models),
        "models_requested": [_model_tag(model) for model in models],
        "frozen_bayes_models": [
            {"model": _model_tag(model), "P": model[0], "S": model[1]}
            for model in FROZEN_BAYES_MODELS
        ],
        "wide_columns": list(WIDE_COLUMNS),
        "shards": {},
    }


def _default_probe_factory(P: int, S: int, config: H1OffsetConfig) -> object:
    return pl.Probe(P, S, device=config.device, batch_size=config.batch_size)


def _checkpoint_identity(probe: object) -> dict[str, object]:
    """Capture the resolved checkpoint label and the strongest available revision metadata."""

    label = str(
        getattr(
            probe,
            "label",
            f"{type(probe).__module__}.{type(probe).__qualname__}",
        )
    )
    model = getattr(getattr(probe, "pipe", None), "model", None)
    model_config = getattr(model, "config", None)
    source = getattr(model_config, "_name_or_path", None)
    revision = getattr(model_config, "_commit_hash", None)
    identity: dict[str, object] = {"label": label}
    if source:
        source_path = Path(str(source)).expanduser()
        if source_path.exists() and source_path.is_dir():
            resolved = source_path.resolve()
            identity["source_kind"] = "local_directory"
            identity["source"] = resolved.name
            identity["weights_tree_sha256"] = _directory_sha256(resolved)
        else:
            identity["source_kind"] = "remote_or_named"
            identity["source"] = str(source)
    if revision:
        identity["revision"] = str(revision)
    if model_config is not None and callable(getattr(model_config, "to_dict", None)):
        config_json = json.dumps(
            model_config.to_dict(), sort_keys=True, separators=(",", ":"), default=str
        )
        identity["config_sha256"] = hashlib.sha256(
            config_json.encode("utf-8")
        ).hexdigest()
    return identity


def collect_paired_offsets(
    out_dir: Path | str,
    config: H1OffsetConfig | None = None,
    models: Sequence[tuple[int, int]] = FROZEN_BAYES_MODELS,
    *,
    force: bool = False,
    probe_factory: Callable[[int, int, H1OffsetConfig], object] | None = None,
) -> pd.DataFrame:
    """Collect, shard, resume and merge the paired fixed/adaptive H1 data.

    ``probe_factory`` is injectable for tests.  Its signature is ``(P, S,
    config) -> probe`` and the returned object must expose ``P``, ``S``,
    ``recovery(...)`` and, optionally, ``close()``.
    """

    cfg = _cfg(config)
    selected = _normalise_models(models)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    manifest_path = out / MANIFEST_NAME
    existing_shards = [_shard_path(out, P, S) for P, S in selected]
    previous_manifest: dict[str, object] | None = None

    if not force and any(path.exists() for path in existing_shards):
        if not manifest_path.exists():
            raise ValueError(
                "cannot resume H1 shards without h1_offset_manifest.json; use force=True"
            )
        previous_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if previous_manifest.get("design_fingerprint") != _design_fingerprint(
            cfg, selected
        ):
            raise ValueError(
                "existing H1 shards use a different config/model subset/schema; "
                "choose a new output or force=True"
            )

    manifest = _new_manifest(cfg, selected)
    _atomic_json(manifest, manifest_path)
    factory = probe_factory or _default_probe_factory
    frames: list[pd.DataFrame] = []

    try:
        for P, S in selected:
            tag = pl.model_tag(P, S)
            shard = _shard_path(out, P, S)
            if shard.exists() and not force:
                previous_shard = (
                    (previous_manifest or {}).get("shards", {}).get(tag, {})
                )
                if (
                    previous_shard.get("design_fingerprint")
                    != manifest["design_fingerprint"]
                ):
                    raise ValueError(
                        f"{tag}: shard design fingerprint is missing or stale"
                    )
                previous_checkpoint = previous_shard.get("checkpoint")
                if not isinstance(
                    previous_checkpoint, dict
                ) or not previous_checkpoint.get("label"):
                    raise ValueError(
                        f"{tag}: shard checkpoint identity is missing; use force=True"
                    )
                probe = factory(P, S, cfg)
                try:
                    actual = (int(getattr(probe, "P")), int(getattr(probe, "S")))
                    if actual != (P, S):
                        raise ValueError(f"{tag}: probe loaded geometry {actual}")
                    checkpoint = _checkpoint_identity(probe)
                finally:
                    close = getattr(probe, "close", None)
                    if callable(close):
                        close()
                if checkpoint != previous_checkpoint:
                    raise ValueError(
                        f"{tag}: resolved checkpoint changed since the shard was written; "
                        "choose a new output or use force=True"
                    )
                frame = pd.read_parquet(shard)
                validate_paired_data(frame, cfg)
                state = "reused"
            else:
                probe = factory(P, S, cfg)
                try:
                    actual = (int(getattr(probe, "P")), int(getattr(probe, "S")))
                    if actual != (P, S):
                        raise ValueError(f"{tag}: probe loaded geometry {actual}")
                    checkpoint = _checkpoint_identity(probe)
                    frame = _collect_geometry(probe, cfg)
                    _atomic_parquet(frame, shard)
                finally:
                    close = getattr(probe, "close", None)
                    if callable(close):
                        close()
                state = "written"

            frames.append(frame)
            manifest["shards"][tag] = {
                "status": state,
                "file": str(shard.relative_to(out)).replace("\\", "/"),
                "rows": int(len(frame)),
                "lock_sites": int(frame["f_lock"].nunique()),
                "design_fingerprint": manifest["design_fingerprint"],
                "checkpoint": checkpoint,
            }
            manifest["updated_at"] = _timestamp()
            _atomic_json(manifest, manifest_path)

        merged = pd.concat(frames, ignore_index=True)
        merged = merged.sort_values(
            ["model", "generator", "bg_id", "f_lock", "phase_idx"]
        ).reset_index(drop=True)
        summary = validate_paired_data(
            merged,
            cfg,
            require_all_models=set(selected) == set(FROZEN_BAYES_MODELS),
        )
        _atomic_parquet(merged, out / MERGED_NAME)
        manifest["status"] = "complete"
        manifest["summary"] = summary
        manifest["merged_file"] = MERGED_NAME
        manifest["merged_design_fingerprint"] = manifest["design_fingerprint"]
        manifest["updated_at"] = _timestamp()
        _atomic_json(manifest, manifest_path)
        return merged
    except Exception as exc:
        manifest["status"] = "failed"
        manifest["error"] = f"{type(exc).__name__}: {exc}"
        manifest["updated_at"] = _timestamp()
        _atomic_json(manifest, manifest_path)
        raise


__all__ = [
    "FROZEN_BAYES_MODELS",
    "H1OffsetConfig",
    "LONG_COLUMNS",
    "MANIFEST_NAME",
    "MERGED_NAME",
    "WIDE_COLUMNS",
    "collect_paired_offsets",
    "design_fingerprint",
    "select_common_sites",
    "synthetic_paired_data",
    "to_long_contrasts",
    "validate_paired_data",
]
